### ISSUE TITLE
Add a prettier configuration

### ISSUE THREAD

**Issue by cfanoulis** [hackclub/sinerider#106]
Honestly, not having to worry about styling is great. Without wanting to bikeshed a lot, would everyone be on board with using prettier with some sane-er configuration (ie, I love [@sapphire's](https://www.npmjs.com/pakcage/@sapphire/prettier-config) config) to save on time spent trying to keep a (uniform) code style?

**Comment by polytroper** [comment]
Sorry for taking forever to reply to this, but yes I definitely approve of this.

**Comment by rithulkamesh** [comment]
https://github.com/hackclub/sinerider/pull/161

**Comment by karamassie** [comment]
#161 was closed
