### ISSUE TITLE
Add Metatags for search and preview results

### ISSUE THREAD

**Issue by maxwofford** [hackclub/sinerider#121]
Awesomely, we're the first result for "sinerider". Let's do something nice with the space.

<img width="885" alt="Screen Shot 2022-07-18 at 22 48 47" src="https://user-images.githubusercontent.com/5891442/179653632-07963cad-6698-4d62-a1ef-ecf1994bc75f.png">
<img width="718" alt="Screen Shot 2022-07-18 at 22 48 31" src="https://user-images.githubusercontent.com/5891442/179653642-8798dfb7-3902-40ee-873e-c8eb801f3be2.png">

**Comment by IamTregsthedev** [comment]
What do you want to see when you search it? any ideas?

**Comment by maxwofford** [comment]
@IamTregsthedev want to take this on?

Go ahead and write a first draft (check out the github description for a starting point) and we can edit in PRs!

**Comment by maxwofford** [comment]
Oh, this should also include...

- [ ] Favicon
- [ ] Open Graph image (cc @ClaireBookworm for whatever image we've been using so far)
- [ ] Open Graph description

**Comment by ClaireBookworm** [comment]
I can work on the unfurl images yeah! I'll reach out to the artists.

**Comment by IamTregsthedev** [comment]
I would love to!

**Comment by karamassie** [comment]
@IamTregsthedev if you're committing to doing this, pls assign it to yourself. TYYYY

**Comment by ClaireBookworm** [comment]
I've updated the description and added some rudimentary meta-tags!

**Comment by maxwofford** [comment]
Fixed by #131
