### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by dmadisetti** [hackclub/sinerider#127]
Super cool, I did all the levels except Level 8 of constant lake (it wouldn't load, and was the only level that was broken for me)

Just some unsolicited feedback from some random on the internet (I would make this a discussion post if you had the option)

## Features?
- Click to figure out coordinates
- Save previous attempts (I didn't see an issue for this)
- scoreboard for times
- Make it easier to play around with constants? For some of the harder ones, I had something I knew would work, but had to fiddle with the constants. If I could define a general constant like `a`, and then have a slider for it, that would be awesome.
- Kinda wanted to use differential operators/ relations? but I think that's beyond scope
- A level in space with no gravity (or with orbital mechanics!) would also be cool

## Story
The story was super cute! But I didn't think it featured too much, and there was no closure, but it's a nice touch. I realized I missed some of the dialog and well, but maybe that's me. My only complaint is I didn't think the pacing was super consistent, I thought level difficulties were all over the place.

## Gameplay
General tricks I used:

Gaussian for little bumps to move characters
$$N(x) = e^{\frac{(x+a-t)^2}{b}}$$

Sigmoid for limiting behavior
$$\frac{1}{1+e^{-t}}$$

Exponential for just a wall lol
$$e^{x}$$

I played around with using undefined regions, and that was interesting. I think I used

$$Y=((x-a)^2 - r^2)^{1/2}$$

to make a little bucket I could move around. Lol, you can use this for instantaneous velocity too:

$$-.5-5\left(\left(x-23t\right)^2-1\right)^{\left(\frac{1}{2}\right)}+\frac{x}{2}$$

(this solves one of the parabola ones in the mountains in 0.2s)

---

Fav was definitely the rivers of time.

Keep doing cool things. Looking forward to the released version!

**Comment by polytroper** [comment]
This is all really great feedback, thank you! Will be opening an issue for clicking to get coordinates
