### ISSUE TITLE
Show level name (for while in development)

### ISSUE THREAD

**Issue by maxwofford** [hackclub/sinerider#129]
Currently the level names aren't shown in the game. It'd be really helpful while going through GH to have the names instead of referring to things like "the first mountain level" or "level 6" (the path branches, so numbers don't work).

I'd love to have the level name show up while I'm local hosting or on sinerider.hackclub.dev (or whatever future dev domain we have)

**Comment by polytroper** [comment]
This would indeed be helpful.
