### ISSUE TITLE
better indicate you've probably failed

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#130]
failed state: for a new user, they might not know they've 'failed' - unclear that we need to hit the T= button again.

**Comment by maxwofford** [comment]
We don't currently know the user has failed, but maybe we can have a gentle "reminder" to restart if certain conditions are met:

- level has progressed past a certain time (ex. 5 sec) without victory
- sledder is over a certain distance from any goal (ex. 1000px)

Just doodling with ideas here– if anyone has other ideas for triggers please comment!

**Comment by parge0** [comment]
For every level, store the correct solution and calculate how long it should take for the level to complete.
If it takes more than twice that amount of time, show a fail screen.

**Comment by polytroper** [comment]
Agreed. We need a button to slide out from the top that says "Try Again" or something
