### ISSUE TITLE
Change the name of the master branch to main

### ISSUE THREAD

**Issue by brunoblaise** [hackclub/sinerider#132]
**As of October 1, 2020**, any new repository you create on GitHub.com will use main as the default branch. Existing repositories that have master set as the default branch will be left as is. That is why I was suggesting we could change the name of the branch from master to main.

A YouTube video that explains it well:  [Link](https://www.youtube.com/watch?v=hZznWbEGv1U)

**Comment by polytroper** [comment]
Done
