### ISSUE TITLE
Issue Templates ⚠

### ISSUE THREAD

**Issue by IAmTamal** [hackclub/sinerider#133]
## Issue Templates are awesome to have

 - Since there are alot of folks contributing to this **Opensource** project i would suggest we have `ISSUE TEMPLATES`
 - That way we can categorize the issues more and manage it more decently.

## Here's how the templates looks : 

![image](https://user-images.githubusercontent.com/72851613/186455418-275c5798-4785-4bbf-af3f-8ae10115cdb4.png)

## Here's how the forms looks : 

![image](https://user-images.githubusercontent.com/72851613/186455509-71990d5e-1993-4ea7-bf4c-6ac6a7c5f5f6.png)

**Comment by maxwofford** [comment]
@IAmTamal Feel free to submit a PR for this & tag me– I'm happy to review!

**Comment by IAmTamal** [comment]
> 

Sure, i will do both 💚

**Comment by karamassie** [comment]
I'd love to learn how to use templates though too :)

**Comment by IAmTamal** [comment]
> I'd love to learn how to use templates though too :)

Issue Templates are more like google forms, there are input fields and such so that folks new to contributions can easily  ! 
Also, we can easily understand which issue is of which **aspect** and how that will impact the project !
