### ISSUE TITLE
Level one: windmill is missing its spinning windmill :)

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#134]
NOTES: (from @alhardwarehyde) from 3/15 sync with @polytroper: Sprite Animation for Intro Level. Windmill and Smoke from the Chimney. High Priority, Nice to Have but not Blocking Launch.

creenie of topless windmill
<img width="481" alt="Screen Shot 2022-08-24 at 11 52 56 AM" src="https://user-images.githubusercontent.com/99233707/186464713-1312c672-b61a-4d42-bf0e-a7c25394223a.png">
 art asset :
![IMG_1982](https://user-images.githubusercontent.com/99233707/186464843-a34dc136-7167-428b-a0e4-d2841bccb0b5.PNG)

**Comment by polytroper** [comment]
Wait why did this one get closed? This hasn't gotten done yet because it turned out to be more complicated than expected. The windmill has to move/scale with the fake parallax effect of the background, which is a bit of a headache that I am still seeking tylenol for.

**Comment by karamassie** [comment]
@Benjamin-Rosenfeld -- can you have a crack at this. if not, just unassign it . TYSM

**Comment by Benjamin-Rosenfeld** [comment]
yes, i will definitely try and fix it!
