### ISSUE TITLE
A bump in the graph teleports a character up

### ISSUE THREAD

**Issue by TvoozMagnificent** [hackclub/sinerider#139]
### Description

Given a function like $x+\frac{\left(\frac{\left|x\right|}{x}-\frac{\left|x-3\right|}{x-3}\right)}{2}\cdot100$, the player will teleport.

[This](https://www.desmos.com/calculator/y5mnzhgrcq) explains it clearer.

**Comment by polytroper** [comment]
Ugh yeah haha this is one of the challenging edge cases with the way the rigidbody interactions with the graph are implemented. Good issue, unlikely to see resolution now but leaving this open.

**Comment by polytroper** [comment]
Closing because this class of issues is unlikely to be resolved anytime soon.
