### ISSUE TITLE
Click/tap for coordinates

### ISSUE THREAD

**Issue by polytroper** [hackclub/sinerider#156]
### Description

Clicking or tapping on the screen should give you the coordinates of that point and display axes at that origin

**Comment by GalaxyGamingBoy** [comment]
I'll take this

**Comment by karamassie** [comment]
@polytroper do we still want this feature? @GalaxyGamingBoy how far along did you get?

**Comment by GalaxyGamingBoy** [comment]
Progress has been slow with exams sadly, so I don't know if I'll actually be able to complete it :(

**Comment by alhardwarehyde** [comment]
related to #75

**Comment by Benjamin-Rosenfeld** [comment]
If its okay ill take this one
