### ISSUE TITLE
White text in the desert

### ISSUE THREAD

**Issue by polytroper** [hackclub/sinerider#158]
### Description

We need all the text in this biome to be white.

### Screenshots

<img width="933" alt="image" src="https://user-images.githubusercontent.com/15720465/212171150-4d4c45a9-2805-43e7-bf93-a63a53d4c866.png">

**Comment by GalaxyGamingBoy** [comment]
May I take this issue?

**Comment by polytroper** [comment]
Go for it

**Comment by GalaxyGamingBoy** [comment]
Pull Request #169 should fix the issue
