### ISSUE TITLE
Add the hint sliders to many/most puzzles in the first several biomes

### ISSUE THREAD

**Issue by polytroper** [hackclub/sinerider#159]
### Description

In the first few levels you can see these lovely hint sliders made by @neelr. Well, we need those sliders to be filled out for a large number of levels! Basically, all but the last few puzzles in the Western Slopes, the Valley of the Parabola, the Sinusoidal Desert, and the Logistic Dunes need one of these helpful sliders to convey the key concept required to solve that level.

This is a super duper important one! We need someone to really understand and own the educational design here, who really likes writing these mathematical functions and figuring out exactly which function makes a good hint for each puzzle.

### Screenshots

<img width="914" alt="image" src="https://user-images.githubusercontent.com/15720465/212186127-4b99e01b-bc9e-4a3a-8d5a-c415a37acf1b.png">

**Comment by alhardwarehyde** [comment]
@polytroper is this issue good to close? We added sliders to a lot more levels and we have a separate issue about the Time Puzzles - #215
