### ISSUE TITLE
Parsing Error?

### ISSUE THREAD

**Issue by cole-wilson** [hackclub/sinerider#18]
Hello! I was just testing out this (very cool) game, and I noticed a problem with the level where you use a slope of 0.5. If I write $Y=-\frac{1}{2}x$ instead of $Y=-0.5x$ it breaks, but -0.5 seems to work. I believe that it's parsing it as $Y=-\frac{1}{2x}$ instead of $y=-\frac{1}{2}x$.
![image](https://user-images.githubusercontent.com/49500253/173157966-6d0359cd-d121-4c23-afbc-082a96d4e22d.png)

**Comment by cfanoulis** [comment]
can reproduce.

**Comment by polytroper** [comment]
Yup this needs fixing. I believe @profsucrose has a fix ready for it in his branch

**Comment by polytroper** [comment]
Duplicate
