### ISSUE TITLE
you should not be able to  click the stop button in volcano level

### ISSUE THREAD

**Issue by ivoinestrachan** [hackclub/sinerider#182]
### Description

Stop button should be removed in volcano level

**Comment by alhardwarehyde** [comment]
<img width="1322" alt="Screenshot 2023-03-14 at 2 32 11 PM" src="https://user-images.githubusercontent.com/122998778/225103750-1a606d96-96b9-499b-97ef-0719222ca14d.png">
Clothing this because there is no stop button in the Volcano Level Currently.
