### ISSUE TITLE
Add "Mobile Not Supported" popup on loading screen when visiting the site from Mobile

### ISSUE THREAD

**Issue by CoolCoderSJ** [hackclub/sinerider#186]
### Description

When on mobile, anything clicked on the keyboard isn't going into the equation box.

### Screenshots

https://user-images.githubusercontent.com/53063247/221025439-b76910e2-e676-45e1-ac08-d38271ba504c.mp4

### Additional information

Device: Pixel 6a
Browser: Kiwi (Chromium), Chrome
OS: Android 13

**Comment by karamassie** [comment]
@grymmy -- polytroper has a library that might be a global fix for all keyboard issues on mobile.

**Comment by grymmy** [comment]
@polytroper @karamassie mentioned there is a plan here already.  Can commentary be added?

(also - please feel free to remove yourself as an assignee once you've added the info, Chris)

**Comment by polytroper** [comment]
Closed for now, will reopen if mobile doesn't work out
