### ISSUE TITLE
BUG: "show all" unlock levels << dev state to fix before ship

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sinerider#187]
### Description

"show all" unlock levels

NOTES: @alhardwarehyde Keep Button add dialogue box/language "this will unlock all levels are you sure you want to do this"

### Screenshots

https://user-images.githubusercontent.com/88567622/221298209-1d4724fa-d6b5-44dc-a85b-b1248bec368c.mp4

**Comment by karamassie** [comment]
@polytroper should we make an issue to turn this off before it ships?

**Comment by alhardwarehyde** [comment]
@karamassie Chris and I covered this- updating the issue with notes to make what needs to happen more clear.

**Comment by polytroper** [comment]
@cytronicoder Could you add another one of your awesome dialogs for the SHOW ALL button, saying "Are you sure you want to unlock all levels?"

**Comment by polytroper** [comment]
(if so, please assign yourself)

**Comment by Benjamin-Rosenfeld** [comment]
ill try and copy cytronicoder best as i can, it will be done tonight

**Comment by alhardwarehyde** [comment]
@Benjamin-Rosenfeld did this get done?

**Comment by Benjamin-Rosenfeld** [comment]
done in pr
