### ISSUE TITLE
[FEATURE] Use lowercase `t` for time variable

### ISSUE THREAD

**Issue by SamDev-7** [hackclub/sinerider#188]
### Description

Currently, in the bottom right, capital `T` is used to for time. (`T=5.2`)

To be consistent with equations (which only permit `t`), lowercase `T` should be used to track time. (`t=5.2`)

### Screenshots

![image](https://user-images.githubusercontent.com/66446458/222012768-e33fd4fa-b61c-4152-8a56-fd227421b22d.png)

**Comment by polytroper** [comment]
This is an excellent point, thank you! Will change shortly

**Comment by polytroper** [comment]
Fixed
