### ISSUE TITLE
Constant Lake not loading 

### ISSUE THREAD

**Issue by Patcybermind** [hackclub/sinerider#189]
### Description

Exactly what it is i click on it and it looks like it works and then it just freezes

### Screenshots

![image](https://user-images.githubusercontent.com/97562509/222317483-00478baf-75af-4540-b026-959cc2457af7.png)
![image](https://user-images.githubusercontent.com/97562509/222317752-f0b2e285-f9f4-4454-94d8-ea5b48c170b2.png)

### Additional information

I am on linux, on firefox and i use the pop os distro if that changes anything
I hope it's easy to fix!

**Comment by khrj** [comment]
![image](https://user-images.githubusercontent.com/44947946/222643879-d8e34e6e-d1f8-4389-8679-6164c062e325.png)

I have the same issue

**Comment by karamassie** [comment]
@polytroper is this an OS thing or something that was broken temporarily ?

**Comment by karamassie** [comment]
heya! @khrj and @Patcybermind  , mind to check if this is still happening? and once again, if it is, can you provide console logs again? super appreciate your help.

**Comment by polypixeldev** [comment]
I'm having the same issue on Firefox, Ubuntu 22.04, Intel Xe Integrated graphics - attached are my console logs
[sinerider.txt](https://github.com/hackclub/sinerider/files/11024423/sinerider.txt)

**Comment by camdan-me** [comment]
I have encountered this before but can't seem to reproduce at the moment.

**Comment by Patcybermind** [comment]
i made a screencast here it is
[constant_lake_not_loading.txt](https://github.com/hackclub/sinerider/files/11033651/constant_lake_not_loading.txt)

**Comment by polypixeldev** [comment]
For me the timer in the lower right corner gets set to abt t=-26 when I click on the circle, and if I hold my mouse down the timer goes up but nothing happens when it crosses zero, just stays red.

**Comment by Omay238** [comment]
I think this issue happens with all cutscenes.

**Comment by polytroper** [comment]
@polypixeldev this is currently the intended behavior but is slated to change. See https://github.com/hackclub/sinerider/issues/266

**Comment by polytroper** [comment]
@profsucrose Is it possible that this error—which happens in my browser as well—is breaking some browsers but not others? Can we address this and see if people's problems resolve?

`Uncaught Unable to find location of attribute 'aTexCoords' in shader program GLUtils.js:122:12`

**Comment by Patcybermind** [comment]
weird, the screencast didnt get uploaded
[Screencast from 2023-03-21 05:03:39 PM.webm](https://user-images.githubusercontent.com/97562509/227358234-9cdd4c07-1a0a-4797-b1fb-22c7b3d0aec7.webm)

here it is:

**Comment by Patcybermind** [comment]
there

**Comment by polypixeldev** [comment]
I've done some digging into WebGL, and it seems that it has to do with optimizations on Linux. Can anyone else test this out on different browsers on Windows and Mac to see if this is the case?

**Comment by profsucrose** [comment]
Yes, this bug had to do with WebGL optimizations done by Firefox on Linux (I have no idea why only on that specific browser and OS? I couldn't reproduce the bug through Firefox on macOS nor Chromium on Linux, but just Firefox on Linux) as there was a texture attribute not being used in the shader, and as a result it was being silently removed by the shader compiler. This issue should now be fixed though (or at least it works on my Linux machine now; commit 6620c1c).

**Comment by polytroper** [comment]
We had someone on firefox/linux encounter this bug today (like 2 hrs ago)
on the main dev build. Can someone else verify that this is fixed for them
too?

**Comment by khrj** [comment]
It's fixed for me.

**Comment by polypixeldev** [comment]
It's fixed for me as well

**Comment by Patcybermind** [comment]
it works now!
and the level is nice!
