### ISSUE TITLE
Level LOGISTIC_PARABOLA Solves Itself

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#194]
### Description
From HQ Playtest 3/9
LOGISTIC_PARABOLA is solved by default with zero changes

### Screenshots

<img width="286" alt="Screenshot 2023-03-14 at 10 45 30 AM" src="https://user-images.githubusercontent.com/122998778/225038205-e650c2f6-39be-4ca9-8fde-448e7e6b3e16.png">

**Comment by polytroper** [comment]
Fixed
