### ISSUE TITLE
Slow Reset Depending on Function

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#198]
### Description
From HQ Playtest 3/9
On TIME_SIN_TRANSLATE_X I used the function \frac{\sin \left(x-t+4\right)}{\frac{t}{10}}. It takes a really long time to reset that level after that level!
and
On TIME_PARABOLA_NEGATOR level, if you run the level with the function -\left(\frac{x+t}{4-t}\right)^2 and wait 10 seconds, it can’t reset

**Comment by polytroper** [comment]
Fixed.
