### ISSUE TITLE
[FEATURE] Modify "About Last Night" Line in SLOPE_HIGHER

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#200]
### Description
From HQ Playtest 3/9
Line Reads as Confusing, Players think they missed something. Line Needs Reworking, maybe cut "about last night"?

### Screenshots

<img width="603" alt="Screenshot 2023-03-14 at 12 24 30 PM" src="https://user-images.githubusercontent.com/122998778/225071845-5c75a3a2-76b5-4b5d-8acb-0028138e6be2.png">

**Comment by agentblack6000** [comment]
This issue is fixed, the line is replaced with "Hey, I'd like to apologise"
