### ISSUE TITLE
Click Sound Lags when Pressing the Reset Button

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#202]
### Description
From HQ Playtest 3/9
Sound has ~500ms to 1000ms lag from button press on Firefox

### Screenshots

<img width="479" alt="Screenshot 2023-03-14 at 12 46 04 PM" src="https://user-images.githubusercontent.com/122998778/225077255-80af12cb-56d8-4fd1-a9e7-c1343f9fed50.png">

**Comment by polytroper** [comment]
Resolved
