### ISSUE TITLE
[FEATURE] Volume Slider Needs to be Higher Opacity

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#203]
### Description
From HQ Playtest 3/9
Volume Controls Need to be Higher Opacity

**Comment by imsidkg** [comment]
Can I work on this issue?

**Comment by alhardwarehyde** [comment]
@imsidkg go for it!

**Comment by alhardwarehyde** [comment]
@imsidkg Actually we're closing this one out but going to tag you in a similar issue if you want to tackle that one instead

**Comment by alhardwarehyde** [comment]
@imsidkg are you interested tackling this issue https://github.com/hackclub/sinerider/issues/209 instead?
