### ISSUE TITLE
[FEATURE] Hint Button/Sliders Don't Match

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#204]
### Description
From HQ Playtest 3/9
Make the Colors Match to make it look more cohesive.

### Screenshots

<img width="619" alt="Screenshot 2023-03-14 at 12 33 48 PM" src="https://user-images.githubusercontent.com/122998778/225078655-ba3661be-9682-40e4-849e-757e99cfd9dd.png">
<img width="622" alt="Screenshot 2023-03-14 at 12 33 36 PM" src="https://user-images.githubusercontent.com/122998778/225078677-b5a55c9a-d7fa-4504-aa37-77ad1c0097f5.png">

**Comment by Omay238** [comment]
Would all yellow or all green be preferred?

**Comment by Omay238** [comment]
I personally think yellow is better looking.

**Comment by alhardwarehyde** [comment]
@camdan-me thoughts? I think this relates to your work on #286?

**Comment by camdan-me** [comment]
It does relate, and honestly I haven't yet come up with a good way to integrate hints. If anyone has suggestions based on the new UI idea I'd love to hear them.

**Comment by alhardwarehyde** [comment]
@polytroper can you weigh in here?

**Comment by polytroper** [comment]
What if we have a second, non-editable box pop down from the top that looks just like the equation bar at the bottom, except with a second row under the `Y=<equation>` row for the slider?

**Comment by polytroper** [comment]
Maybe a lil tabby button that pokes out from the top (kinda like the SHOW ALL button on the map). When you click on that, it slides up out of view and the hint stuff slides down into view?

**Comment by alhardwarehyde** [comment]
@Omay238 did you see Chris's feedback? Is this something you can work on?

**Comment by Omay238** [comment]
Maybe. Definitely harder than just changing color. I'll try but no guarantees.

**Comment by alhardwarehyde** [comment]
@Omay238 just checking in on this- is this something you're still working on?

**Comment by polytroper** [comment]
Closed because covered by #286
