### ISSUE TITLE
[FEATURE] Design and implement final Loading Screen

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#207]
The loading screen needs to:
* Load quickly
* Communicate load status of the game (percentage, errors)
* Link to the daily puzzle on twitter/reddit (open in a new tab)
* Show a screenshot of the daily puzzle
* Descriptive blurb
* Hack Club flag
* Link to GitHub
* Version number

Anything else?

**Comment by karamassie** [comment]
Also discussed a link to HC and the GH here.

**Comment by camdan-me** [comment]
On this note, maybe someone should make a full on homepage explaining and promoting the project, with a prominent "play" button. Maybe the homepage could also set a cookie that automatically takes you to the game on repeat visits.

**Comment by polytroper** [comment]
Keep it simple, the game is the homepage. It speaks for itself. We can have a separate "About" page but sinerider.com should deliver you to gameplay absolutely as quickly as possible

**Comment by alhardwarehyde** [comment]
We also need to think about where the leaderboard is going to go
