### ISSUE TITLE
[FEATURE] Completely Hide Volume Control when Not Hovering Over it

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#209]
### Description
From HQ Playtest 3/9
Hide the Volume Control when Not in Use

**Comment by alhardwarehyde** [comment]
@ShubhamPatilsd are you good to implement this?

**Comment by camdan-me** [comment]
This may be rendered obsolete by #286

**Comment by ShubhamPatilsd** [comment]
something urgent popped up, i am no longer able to complete this issue, so sorry

**Comment by alhardwarehyde** [comment]
@ShubhamPatilsd no worries! Thank you for letting us know and unassigning yourself

**Comment by alhardwarehyde** [comment]
Resolved by #326
