### ISSUE TITLE
[FEATURE] Differentiate Cutscenes from Levels on World Map

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#218]
### Description
From HQ Playtest 3/9
Change the shape from Circles to Hexagons to make the differences more clear

**Comment by polypixeldev** [comment]
I'll try to work on this issue

**Comment by polytroper** [comment]
@polypixeldev do you have a good sense of how to tackle this?

Hint: you can do it all just by changing the `draw` function of `LevelBubble.js` (with maybe one extra Vector2 allocated during the LevelBubble instantiation). LMK if you need more info to get started.

**Comment by polypixeldev** [comment]
Ok, thanks! I'm still trying to get familiar with the codebase, but I'm understanding everything.
