### ISSUE TITLE
If Enter In Wrong Formula Some Levels Will Go On Forever.

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#221]
### Description
From HQ Playtest 3/9
I.e Level 1. Suggest adding a timeout after player hits run

### Screenshots

![Screenshot 2023-03-14 at 3 27 10 PM](https://user-images.githubusercontent.com/122998778/225116793-3f4f244c-86d0-4ffa-909f-4e7151e5ee54.png)

**Comment by polytroper** [comment]
As designed. Could try to work out some kind of timeout system but it would take some design iteration to make that feel right. Once players internalize the mechanics of the game, this is no longer an issue, which makes me think the real solution is just to explain the game better.
