### ISSUE TITLE
Fix Text Alignment in SLOPE_STEEPER

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#223]
From Meeting with @polytroper 3/16
![Image](https://user-images.githubusercontent.com/122998778/225641934-11d6b614-f933-42df-8406-0e4d32be3c7e.png)

**Comment by polypixeldev** [comment]
I can't reproduce this issue on my computer - Firefox on Ubuntu 22.04
![image](https://user-images.githubusercontent.com/79737178/226770043-f8d3f478-ed87-4013-aa16-18c5d19cf961.png)

**Comment by camdan-me** [comment]
CNR, Chrome/Win11 https://cam.is-ne.at/5YS5bs_2r.png

**Comment by alhardwarehyde** [comment]
@polytroper thoughts on this issue?

**Comment by alhardwarehyde** [comment]
This is happening on Safari Version 16.3 (18614.4.6.1.6). May just be a Safari thing

**Comment by polypixeldev** [comment]
Is it a css vendor prefix thing?

**Comment by camdan-me** [comment]
Could be, https://github.com/postcss/autoprefixer might be a smart way to solve prefix issues

**Comment by polytroper** [comment]
Fixed
