### ISSUE TITLE
Ordered Path Goals, Letter Movement Needs Fixing

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#224]
### Description

from 3/16 Meeting with @polytroper 
On ordered path goals, the letters move independently and incorrectly relative to the goal

**Comment by alhardwarehyde** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122998778/226447962-a792c04b-0549-4b49-8606-7520d627dee1.png">

**Comment by polytroper** [comment]
Fixed
