### ISSUE TITLE
Credits Dialogue has temp text on it ("dialogue coming")

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#233]
### Description
From Meeting with @polytroper 3/16
Credit's Dialogue needs to be finished

### Screenshots

<img width="1337" alt="Screenshot 2023-03-16 at 10 51 55 AM" src="https://user-images.githubusercontent.com/122998778/225655739-c2e34909-adae-4249-846d-3c5239e35f7d.png">

**Comment by karamassie** [comment]
@alhardwarehyde can you test if "dialog coming" has been replaced with actual dialog pls

**Comment by alhardwarehyde** [comment]
![Image](https://user-images.githubusercontent.com/122998778/234025014-949ee39a-1d4a-40a5-a16f-8626448ed45b.png)

Still missing Dialogue
