### ISSUE TITLE
VOLCANO: Split Up Tree Sprites

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#244]
### Description

From 3/15 Meeting with @polytroper There are new Split up Tree Sprites that need to be added to the Volcano Level

### Screenshots
<img width="692" alt="Screenshot 2023-03-16 at 2 03 55 PM" src="https://user-images.githubusercontent.com/122998778/225728159-64683c23-bd64-40db-8f31-edcd6f090cdd.png">

**Comment by aileencrivera** [comment]
Completed!
