### ISSUE TITLE
VOLCANO: When Sled Loads, trail appears to the right of the Rock

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#247]
### Description
From 3/15 Meeting with @polytroper
Think It's because the way the sled is getting loaded, but trail shouldn't be there.

### Screenshots

<img width="855" alt="Screenshot 2023-03-16 at 2 56 59 PM" src="https://user-images.githubusercontent.com/122998778/225726634-146537ce-bcfb-4414-8f3a-3f27d629a50a.png">

**Comment by polytroper** [comment]
Fixed
