### ISSUE TITLE
[FEATURE] VOLCANO- Monster's Mouth Needs to be More Clear

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#248]
### Description
From 3/15 Meeting with @polytroper
it's hard to read what is happening with the monster, it should look like it's trying to eat them.

### Screenshots

<img width="637" alt="Screenshot 2023-03-16 at 2 07 17 PM" src="https://user-images.githubusercontent.com/122998778/225727030-d0609c0b-9976-4f80-810e-134e5cd1981b.png">

**Comment by polytroper** [comment]
Fixed
