### ISSUE TITLE
[FEATURE] VOLCANO Sky needs different equation

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#249]
### Description

From 3/15 Meeting with @polytroper, Similar to #226

**Comment by polytroper** [comment]
@camdan-me did you say you had an equation here?

**Comment by camdan-me** [comment]
Yeah- I was just messing around in constant lake till I found this one. I think it's pretty neat.

![image](https://user-images.githubusercontent.com/62811575/229683640-d5dfbf2d-5439-42ee-a86b-f76ebd2e2c16.png)

**Comment by polytroper** [comment]
Looks great, go with that. Please PR it in and merge it yourself.
