### ISSUE TITLE
[FEATURE] VOLCANO: Other Characters Needed at End of Finish Line

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#250]
### Description

From 3/15 Meeting with @polytroper The story centers around a race and they leap over the volcano to catch up, characters are needed at the finish line to sell that story.

**Comment by agentblack6000** [comment]
What exactly do I need to add to the dialogues?

**Comment by polytroper** [comment]
Hey @agentblack6000, I will be handling this one as it requires a lot of context on the story. However, if you are looking for a place to start contributing I encourage you to pick this one up:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15720465/226469645-cacb68e3-9f11-4a5a-b314-bd53fa7de74e.png">

**Comment by alhardwarehyde** [comment]
@polytroper did you see Claire's question?

**Comment by polytroper** [comment]
Done. @camdan-me permission is already obtained.
