### ISSUE TITLE
[FEATURE] Fill in Dialogue in More Puzzle Scenes Outside of Constant Lake

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#255]
### Description

Dialogue trails off after constant lake and is only in cutscenes. Add more dialogue to other levels throughout the game.

**Comment by agentblack6000** [comment]
for this level how does a joke about how it's toasty in their scarfs or the dessert is more dune-y than expected?
<img width="1231" alt="Screenshot 2023-03-28 at 7 53 57 PM" src="https://user-images.githubusercontent.com/102859002/228270268-c5d92179-d590-48ae-a73b-b22d9a7a235e.png">

**Comment by polytroper** [comment]
Love it. Can you start adding lines to scenes and make a draft PR?

The toasty scarves remark should definitely make a callback to the "are you cold?" scene in the Western Slopes.

**Comment by polytroper** [comment]
I wouldn't say the desert is more dune-y, maybe more like "I didn't expect the desert to be so… wavy."

**Comment by karamassie** [comment]
can you close this when done so we can review and test pls @theobaker
