### ISSUE TITLE
[FEATURE] Make cutscene controls clearer

### ISSUE THREAD

**Issue by camdan-me** [hackclub/sinerider#262]
### Description

Cutscenes need a better indicator of what the controls are. Design ideas are welcome

**Comment by Captainexpo-1** [comment]
@camdan-me This seems to already have happened.

**Comment by camdan-me** [comment]
Link PR/Issue?

**Comment by Captainexpo-1** [comment]
Well, I mean that if you go into the first cutscene there are visible controls.

**Comment by Captainexpo-1** [comment]
@camdan-me Just checking in, do you mean that there should be controls on every cutscene?
