### ISSUE TITLE
[FEATURE] Timer button should be visibly disabled (grey) and unclickable in cutscenes

### ISSUE THREAD

**Issue by polytroper** [hackclub/sinerider#266]
### Description

Right now the "t=" button is red and clickable in cutscenes. It should be grey and nonresponsive to make clear that it doesn't do anything in these scenes besides tell you the value of t

**Comment by camdan-me** [comment]
Went ahead and assigned you, also check #268 @martinyis

**Comment by polytroper** [comment]
@martinyis awesome. Do you have a sense of how to get started?

**Comment by martinyis** [comment]
> @martinyis awesome. Do you have a sense of how to get started?

Hey, would you tell them in what file is this button located?

**Comment by polytroper** [comment]
index.html

**Comment by alhardwarehyde** [comment]
Removing the assignment because there has been no movement on this

**Comment by polytroper** [comment]
Assigning @profsucrose because this is part of `Level`

**Comment by Benjamin-Rosenfeld** [comment]
done in pr
