### ISSUE TITLE
Sinerider is not accurately scorable

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#271]
### Description

The sinerider scoring service attempts to score games by time taken to complete puzzles.  Right now it is doing so inaccurately.

### Screenshots

<img width="512" alt="Screenshot 2023-03-22 at 9 58 20 AM" src="https://user-images.githubusercontent.com/43505167/226956312-cb1d2e5a-e3d2-46e9-8431-7e04f3d53fca.png">

**Comment by polytroper** [comment]
Resolved
