### ISSUE TITLE
Allow sinerider-scoring service to process scores in faster-than-realtime

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#272]
### Description

Right now, the solution time equals == amount of time the service takes to score a submission.  

Figure out if there are ways to run the game faster than realtime to reduce the amount of processing time it takes per submission to something more manageable/scalable.

**Comment by grymmy** [comment]
There has been significant progress on this issue.  Two PRs have landed to enable running the game simulation in faster-than-realtime, [one](https://github.com/JosiasAurel/sinerider-scoring/pull/3) in sinerider-scoring and [one](https://github.com/hackclub/sinerider/pull/303) in sinerider (game).  With the current settings we use, this speeds up that portion of scoring by 500%.

However, there is still significant overhead in loading the page, taking upwards of 15-20 seconds on the servers.  I have attempted to add some level of in-memory content caching with minimal effect.  The real holistic fix is not clear to me now but there are still open avenues of investigation to be done, for instance one suggestion re: Max on how to disable sound downloads in the game client.

There are also some deliberate waiting to be done to cut out parts of video that is undesirable, something on the order of 4-5 seconds.

There is also a 5-10 second overhead for video encoding that might be somewhat unavoidable.

My hope is we can get to something like:

- 3-5s page load
- 0.5-6s game simulation
- 5s waiting overhead
- 5-10s video encoding

This would mean best case 13.5s per request, 26s worst-case...  Right now we're at ~25 best, ~40s worst.

**Comment by camdan-me** [comment]
Is there an execution time cap, such as you can't make submissions longer than 60s to prevent the server from hanging on a puzzle that doesn't get solved?

Also, is there a mathematical way to solve the execution time without running the full simulation, then video could be pushed back to after launch?

And for loading, what if you hosted a local instance of Sinerider that the script makes requests to instead of the official instance, since localhost reqs are so much faster?

**Comment by grymmy** [comment]
> Is there an execution time cap, such as you can't make submissions longer than 60s to prevent the server from hanging on a puzzle that doesn't get solved?
There is an execution time cap of 30 real seconds which we can resolve much faster than that (right now we are worst-case 6 sec or so, but we have knobs that can be turned to bring this down even more.  Right now the implementation is very naive, we even save off canvas frames for level/expression combos that are unsolved, whereas it would be more efficient to take two passes (one for fast scoring to prove solving/resolve timeouts ASAP, one for creation of video when it's found to be necessary).

> Also, is there a mathematical way to solve the execution time without running the full simulation, then video could be pushed back to after launch?
No, but for reasons stated above, this isn't actually a real problem.  Running the simulation is fast and we have quite a bit of control over it now.

> And for loading, what if you hosted a local instance of Sinerider that the script makes requests to instead of the official instance, since localhost reqs are so much faster?
You also get that from caching...
