### ISSUE TITLE
[FEATURE] Implement new UI design

### ISSUE THREAD

**Issue by camdan-me** [hackclub/sinerider#286]
### Description

Implement a new UI design, per discussion with Chris

Requirements:
- Hamburger menu opens map, maybe use a different icon?
- Map has additional settings, such as volume slider and any other menu options
- Reset button should not instantly reset, but should either:
    - Require being clicked twice, with a UI change to indicate another click is necessary
    - Open a modal asking to confirm, modal could be bypassed by holding shift and could be accepted by pressing enter or closed by pressing escape
- Timer should run on click, per current implementation
- The equation box should shrink/expand to fit
- All corners should be equally rounded
- The UI elements should be translucent most of the time, and become opaque on interaction

I also haven't yet figured out a way to integrate the hint UI, if anyone has any ideas

### Screenshots

![sinerider_design_concept_3](https://user-images.githubusercontent.com/62811575/227097476-f258b90f-3a36-4201-9f62-c1cff4fd8b27.png)

**Comment by camdan-me** [comment]
Probably not, I need to focus more on the trailer, but if I take a crack at it I'll assign myself.

**Comment by alhardwarehyde** [comment]
Related to #204

**Comment by cytronicoder** [comment]
Related to #64? I'm going to put the victory UI up sometime today

**Comment by karamassie** [comment]
please post in #gamedev when this is done so we can get eyes / test on it @Captainexpo-1

**Comment by karamassie** [comment]
going to close and move to specific bugs now
