### ISSUE TITLE
Support queueing in the sinerider scoring service

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#287]
### Description

The sinerider scoring service should queue work immediately before servicing scoring requests.  This allows for the service to be able to recover gracefully if the service process is killed, and also would enable the service to actively serve new requests while an old request is still in the process of being serviced.

**Comment by camdan-me** [comment]
On this note, there should probably be an execution time cap, if a certain solution needs to run for an hour that holds up the thread for a really long time.

**Comment by alhardwarehyde** [comment]
closing because we are not queuing in the scoring service, instead in the bots
