### ISSUE TITLE
[FEATURE] Make player have to confirm resetting.

### ISSUE THREAD

**Issue by Captainexpo-1** [hackclub/sinerider#298]
### Description

It would be pretty annoying to accidentally click the reset button or not know that it does and have your entire equation be deleted.

It would probably be a pop up saying something like "Are you sure you want to reset?" with a button below it that would allow you to confirm that you did want to reset.

**Comment by camdan-me** [comment]
Part of #286

**Comment by Captainexpo-1** [comment]
sorry.
