### ISSUE TITLE
Stop dialogue from going off screen in the final cutscene.

### ISSUE THREAD

**Issue by Captainexpo-1** [hackclub/sinerider#301]
### Description

In the final cutscene before the credits, some of the dialogue goes off screen.

### Screenshots

<img width="1440" alt="Screen Shot 2023-03-25 at 12 22 15 PM" src="https://user-images.githubusercontent.com/65295823/227729485-d0056258-ea51-4437-b546-e7b5cc98294a.png">

**Comment by camdan-me** [comment]
This sounds like more of a camera issue, not 100% sure though

**Comment by alhardwarehyde** [comment]
This will probably be part of the final product because I also have this issue on Safari but moving this out of the final product milestone till I look into it more tomorrow.
