### ISSUE TITLE
create trailer (meet with tejas)

### ISSUE THREAD

**Issue by ClaireBookworm** [hackclub/sinerider#31]

**Comment by TejasCreative** [comment]
This issue is specifically for the teaser trailer*, should we make a seperate for the release one?

**Comment by polytroper** [comment]
Yeah I guess we should 🤔

**Comment by maxwofford** [comment]
It seems like this was [done already](https://www.youtube.com/watch?v=8ZLcuP8fDQA&feature=emb_imp_woyt)
