### ISSUE TITLE
incorrect launch date on official page

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#316]
### Description

right now it says FALL 2022. we should fix this with exact ship apr 16

**Comment by Captainexpo-1** [comment]
@polytroper where are the files for the website stored? It doesn't look like the website html is in index.html.

**Comment by polytroper** [comment]
On a different branch called teaser

**Comment by Captainexpo-1** [comment]
ty!

**Comment by alhardwarehyde** [comment]
Resolved via #319
