### ISSUE TITLE
Reddit Bot should cache results of previous scores

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#332]
### Description

See Twitter Bot Issue

**Comment by grymmy** [comment]
I believe this is implemented per my communications with @GalaxyGamingBoy but will confirm today and close when appropriate.

**Comment by grymmy** [comment]
@GalaxyGamingBoy Didn't get around to this the other day - do you know if this is implemented, currently?

**Comment by GalaxyGamingBoy** [comment]
I believe it does work!
Needs further testing of course

**Comment by karamassie** [comment]
@GalaxyGamingBoy can you test please , or post in the channel exactly what steps we should take to test it so we can help?

**Comment by grymmy** [comment]
My understanding is that this is fixed - closing for @GalaxyGamingBoy 's convenience.
