### ISSUE TITLE
[FEATURE] <description>Current access

### ISSUE THREAD

**Issue by Hexagram6294** [hackclub/sinerider#334]
### Description

I am a maths teacher who has regularly used Sinerider for extension and learning support in my classroom.  There is literally nothing like it.  When it was pulled down in favour of the teaser for the upcoming update I was both excited and incredibly frustrated as it is not available right now.  I waited for the first release time (before it was recently updated, but as development is continuing and I have immediate need, I would love to request the following:

Is there any implementation that I can use currently (previous version is preferable)?
Unless it is implemented in a way that is easy to use, is there a guide as to how to get it running?
I have limited coding experience so while I could follow a tutorial, I have been unable to find anything to help me use the current code.

**Comment by Benjamin-Rosenfeld** [comment]
[https://sinerider.hackclub.dev/](url)

**Comment by Benjamin-Rosenfeld** [comment]
This should let you play. I'm so happy to hear teachers are using it for school!

**Comment by Hexagram6294** [comment]
Absolutely!
There is literally nothing like it for high school mathematics.  Finding a good implementation of an educational game is incredibly difficult.  I have been interested in gamification of education for over a decade now, and I've not seen anything that answers high school maths needs as well as this.  It doesn't do everything, but what it does, it does better than anything I've ever seen.

**Comment by grymmy** [comment]
@Hexagram6294 Hi!  So excited and glad to hear you have connected with and loved Sinerider's previous incarnations - we all are SO excited about this new upcoming release too!  If I were you, I'd talk to @polytroper and @karamassie to get a bit of an inside scoop...  Additionally, if you're willing, you can be one of our first real-world beta testers and provide feedback pre-release - we **will** listen to what you have to say!

If and when you do talk to Chris and Kara, be sure to ask them about our unique development team/model here at Hack Club!

Regards,
Graham

**Comment by grymmy** [comment]
@Hexagram6294 - BTW, what issues did you have using and running the code?  Can you tell me what OS you run, we could probably get you up and running with the code, too, like you were wondering about...

**Comment by Hexagram6294** [comment]
I didn't know how, so I didn't attempt.  A friend who is a coder had a look and he advised waiting for release, although I don't think he attempted to get the source code running.
As for getting in touch with Chris and Kara, I don't see any way to contact people through Github directly unless I'm missing something.

**Comment by grymmy** [comment]
@Hexagram6294 can you please reach out via email to me at graham@hackclub.com such that I can help?

**Comment by camdan-me** [comment]
Also- you shouldn't need to run the code locally, you can access the current beta release at https://sinerider.hackclub.dev.

That said, if you really want to, getting the code to run locally is relatively trivial for people familiar with software development (sinerider is a static HTML site), but it does require some sort of server instance such as node, python, or VS Code Live Server. You may not know what that means but if you share it with your developer friend they will and may be able to help you get set up.

Psyched to hear the kind words about sinerider, it's super cool to hear about it being used in classrooms!

**Comment by karamassie** [comment]
I'm kara@hackclub.com ! please do reach out!
