### ISSUE TITLE
[FEATURE] Save game to local storage

### ISSUE THREAD

**Issue by polytroper** [hackclub/sinerider#337]
### Description

We should serialize game state to local storage and automatically restore progress. This would obviate the need for https://github.com/hackclub/sinerider/issues/242

**Comment by camdan-me** [comment]
There should still probably be an optional backup option aside from local storage

**Comment by polytroper** [comment]
It might also make sense to serialize solved levels to the URL. This would
be the backup option, and the way to transfer your save state between
computers.

**Comment by polytroper** [comment]
Very good point. Maybe it checks for an extant save state when a link is
opened, and if one is present it raises a dialogue asking if you would like
to overwrite?

When links are shared from the editor, save state is not serialized.

**Comment by camdan-me** [comment]
I like that idea, what if we also made it so it only serializes the save state if you hit a "copy save link" button or something like that?

**Comment by alhardwarehyde** [comment]
@polytroper so should I close #242?

**Comment by alhardwarehyde** [comment]
@profsucrose What is the status of this? @polytroper

**Comment by alhardwarehyde** [comment]
Closing because appears to be resolved
