### ISSUE TITLE
Levels don't properly load when going between levels in the same biome

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#352]
### Description

From @polytroper in #gamedev slack "this bug happens whenever you go from one level to another in the same biome. Change biomes and it resets. This makes me think it could be related to the music, since that is one of the few things that carries state across levels based on biome"

### Screenshots

![image](https://user-images.githubusercontent.com/122998778/230106374-d8c096ea-a34c-4474-88dd-e63d1cd19030.png)

**Comment by polytroper** [comment]
Update: the relationship is more complicated than outlined above. Biome seems to maybe be a factor for this bug, but it behaves differently in different biomes. Eternal Canyon seems to break immediately when any other Eternal Canyon level is loaded. But not the case for Valley, which only seems to break on certain levels? Maybe related to equation or something…? Very confusing

**Comment by alhardwarehyde** [comment]
closing because its resolved
