### ISSUE TITLE
Leaderboard UI looks rough

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#373]
### Description

A small amount of effort styling what is already there might go a long way in making the leaderboard more presentable.  Some feedback from the team should be listened to.

**Comment by grymmy** [comment]
What specific things should be changed @ivoinestrachan?

**Comment by ivoinestrachan** [comment]
maybe something interactive n reward system like points

**Comment by karamassie** [comment]
is there a design plan here?

**Comment by ivoinestrachan** [comment]
not really but we have a rough design in figma:
https://www.figma.com/file/EaVQX0Zk8NyQX27jMmaInd/leaderboard?node-id=114-108&t=tHF3jZ3o8hgIfVqz-0

**Comment by grymmy** [comment]
Here are the things I think probably should be looked into:

1) Fix issue with non-tilable background (see img below).
2) Ensure leaderboard displays without error and is reasonably usable on mobile.
3) Rename "Length" references to "Expression length"
4) Fix spacing of column names (Position is too close to Name now)
5) Ensure that ties in scoring result in first-submitter winning.
6) Make dropdowns in top right more inviting (its white on white, which doesn't make it obvious that they're interactable)
7) Potentially add video icon + link to the list

<img width="1407" alt="Screenshot 2023-04-13 at 2 01 27 PM" src="https://user-images.githubusercontent.com/43505167/231845251-1aaf41f3-65dd-47cd-b25f-fe887c18e4eb.png">

**Comment by karamassie** [comment]
@ivoinestrachan  can you take this all on, or want me to split them up?

**Comment by grymmy** [comment]
Additional note: when there is no data to display based on drop-down settings, display "no data available" or something like that so it doesn't appear broken but instead making things clear.

**Comment by grymmy** [comment]
I am closing this issue as it is too broad and will create a number of small tasks
