### ISSUE TITLE
Sinerider bot twitter profile uses default image

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#376]
### Description

We should add a reasonable profile pic.

### Screenshots

<img width="557" alt="Screenshot 2023-04-10 at 12 00 18 PM" src="https://user-images.githubusercontent.com/43505167/230941296-776baa87-2c65-4a40-84e9-7c3fea0e0a85.png">

**Comment by developedbytoby** [comment]
Is there a higher resolution version of the favicon?

**Comment by developedbytoby** [comment]
Just made this super simple one! How does it look?
![sr-twitter-pfp](https://user-images.githubusercontent.com/77097223/230942329-def1f1e8-270c-4165-a1f5-27dba20c1c19.png)

**Comment by grymmy** [comment]
Perfect - putting it in for now

**Comment by developedbytoby** [comment]
Awesome! Thank you.
