### ISSUE TITLE
Make twitter bot better at identifying tweets it should reply to

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#378]
### Description

Not all tweets that hashtag sinerider should be replied to, and some should not attempt to be scored at all.  Right now the detection of "valid" tweets to respond to is very naive and needs improvement.

See https://twitter.com/SineriderBot/status/1645471600303587328 as an example of when we go wrong here...

**Comment by grymmy** [comment]
@developedbytoby any chance you could investigate whether or not this still happens?  I believe some of the work you've done validating twitter responses via regex might help here?

**Comment by developedbytoby** [comment]
Should be fixed in the latest PRs!

**Comment by grymmy** [comment]
@developedbytoby if this issue is fixed and deployed to production, please mark this as closed.
