### ISSUE TITLE
Hide level debug info in server recordings

### ISSUE THREAD

**Issue by polytroper** [hackclub/sinerider#379]
### Description

These level name debug things need to disappear when running on the scoring server, so they won't show up in recordings

<img width="370" alt="image" src="https://user-images.githubusercontent.com/15720465/230983535-5d04a610-757d-4dac-b512-2454d6dfa889.png">

**Comment by alhardwarehyde** [comment]
@Benjamin-Rosenfeld what's the status of this?

**Comment by alhardwarehyde** [comment]
Issue will resolve when puzzle points to puzzles hosted on the production build so closing this one out.
