### ISSUE TITLE
Add copy  that we're not supporting mobile

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#397]
### Description

Detect Mobile Browsers and Display Warning Dialogue "We Strongly Recommend Playing This on Something with a Keyboard"

**Comment by karamassie** [comment]
may not be needed. moving off milestone

**Comment by alhardwarehyde** [comment]
Is this issue good to close? I know we have this PR if Mobile doesn't work but seems like it Is? https://github.com/hackclub/sinerider/pull/415

**Comment by karamassie** [comment]
critical for launch
