### ISSUE TITLE
Tool Tips on Victory Screen Need to Hover on Top of Victory Screen

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#398]
### Description

Currently covering Victory Screen

**Comment by cytronicoder** [comment]
There's also this problem of the victory div overlapping the tooltip that the new UI has... cc. @Captainexpo-1 
![Wild New Screenshot 2023-04-13 at 9 46 08 AM](https://user-images.githubusercontent.com/105997270/231625226-64949040-5431-489f-aa79-dc949cf3d737.jpg)

**Comment by karamassie** [comment]
who is taking this one? @Captainexpo-1 or @cytronicoder  ?

**Comment by alhardwarehyde** [comment]
@cytronicoder similarly are you working on this? Also due on the 27th!

**Comment by Benjamin-Rosenfeld** [comment]
Sorry, as the deadline is really soon I knocked this and a bunch of other small issues out. Ready to close after my pr is merged

**Comment by Benjamin-Rosenfeld** [comment]
done in ui change branch
