### ISSUE TITLE
Mouse gets Stuck Using both Hint and Volume Sliders in Levels 

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#399]
### Description

I am on Safari Version 16.3 (18614.4.6.1.6), on a 2022 M2 MacBook Air running Ventura 13.2.1 and this happens on every level I've tried. 

I click on the volume slider OR the hint sliders and my mouse movement only affects the sliders and I cannot click or interact with anything else.

### Screenshots

https://user-images.githubusercontent.com/122998778/231280342-ecae556b-a82b-4ccf-a26b-da8423309288.mov

**Comment by Benjamin-Rosenfeld** [comment]
Sorry about this one, I made a dumb mistake and caused it a while back. Should be good now.

**Comment by Benjamin-Rosenfeld** [comment]
@karamassie I tested my pr on MacOS Ventura in Safari on M1 MBA so it should be a fair test

**Comment by Benjamin-Rosenfeld** [comment]
closed because fixes
