### ISSUE TITLE
Red timer on bottom right should be hidden after level completion

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#401]
### Description

It keeps running after level completion, which seems weird since what we want to time has already been timed...

**Comment by camdan-me** [comment]
Hmm that's a cool idea. Sounds intense processing-wise but could be neat if someone can figure it out.

**Comment by polytroper** [comment]
Fadeout/blur to what?

**Comment by camdan-me** [comment]
If it blurs then the background would just blur. Otherwise probably fade to a semitransparent white overlay.

That's my opinion, grahm might have a different take.

**Comment by grymmy** [comment]
@camdan-me yeah something like that - the focus of the screen would then be the level completion popup, presented mid-screen and perhaps with a bit of a wobble as it displays, to make it pop?

just spitballing here

**Comment by polytroper** [comment]
Whatever we fade to would ideally be at least as visually engaging as just watching the sim continue. Closing as IIRC this has never been a point of confusion in testing, but very willing to redesign if this is in fact a common confounder.
