### ISSUE TITLE
Keyboard displays over formula when running on mobile

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#409]
### Description

Steps to reproduce:
1) Launch sinerider on an Android handset (tested with a Samsung Galaxy S23)
2) Click on the formula.
Expected behavior: Allows for the editing of the formula
Actual behavior: Keyboard displays above formula, preventing you from seeing what you're editing.

**Comment by karamassie** [comment]
mobile generally needs a whole UI review and pass.

**Comment by polypixeldev** [comment]
can't reproduce this issue on samsung galaxy a20, firefox

**Comment by karamassie** [comment]
yeh i had no problem either. closing.
