### ISSUE TITLE
Victory message doesn't go away when next is clicked in twitter levels

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/sinerider#413]
### Description

Even after clicking next, the victory message never goes away and keeps directing to the map.

### Screenshots

[Screencast from 04-12-2023 04:48:05 PM.webm](https://user-images.githubusercontent.com/79737178/231581332-1b5a7898-affe-4c5c-a35f-83b23b388993.webm)
(pointer doesn't show)

**Comment by GalaxyGamingBoy** [comment]
This also seems to be a problem with the Reddit bot also.

**Comment by grymmy** [comment]
@GalaxyGamingBoy I believe you are just waiting on a review/merge to mark this fixed, correct?

**Comment by alhardwarehyde** [comment]
Closing because Fixed
