### ISSUE TITLE
Keyboard blocks bottom half of screen on mobile or has large amount of whitespace

### ISSUE THREAD

**Issue by Benjamin-Rosenfeld** [hackclub/sinerider#416]
### Description

On iOS 16.3 safari, and iPhone 13 Pro the keyboard blocks the bottom half of the screen, and after editing text it moves to the bottom, creating whitespace as seen in the video. 

https://user-images.githubusercontent.com/86892462/232117802-6f472ed7-237e-4b1f-9b68-938e297c376a.MP4

**Comment by karamassie** [comment]
dupe @alhardwarehyde ?

**Comment by alhardwarehyde** [comment]
Closing bc older build
