### ISSUE TITLE
“Edit function here” is in wrong place (over on right, whereas formula is on left)

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#427]
### Description

On https://sinerider-5izo43hmz.hackclub.dev/

**Comment by karamassie** [comment]
@alhardwarehyde was this on mobile only?

**Comment by Captainexpo-1** [comment]
No, it's also on desktop @karamassie

**Comment by Benjamin-Rosenfeld** [comment]
I'm sorry @Captainexpo-1, I forgot this was an issue and accidentally fixed it in a pull request. Can I close?

**Comment by Captainexpo-1** [comment]
definitely! Thank you!
