### ISSUE TITLE
Font in time indicator doesn’t “fit”.  Additionally, red ball should be centered on the ‘0’ instead of shifted slightly to the right.

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#432]
### Description

https://sinerider-5izo43hmz.hackclub.dev/

**Comment by Captainexpo-1** [comment]
This should be fixed now.

**Comment by karamassie** [comment]
@alhardwarehyde can you chck this?

**Comment by Captainexpo-1** [comment]
Actually, It doesn't look like my changes were deployed.

**Comment by alhardwarehyde** [comment]
This looks okay to me- @karamassie thoughts?

![Image](https://user-images.githubusercontent.com/122998778/234024373-188c9d72-5910-4081-94eb-8f41da961c9c.png)

**Comment by alhardwarehyde** [comment]
Update found screenshot of initial issue. This is fixed. Closing
