### ISSUE TITLE
Might make sense to limit the maximum # of characters

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#433]
### Description

Feedback from 4/21 playlets

**Comment by camdan-me** [comment]
Might make people mad if it's a hard limit, it should be bypassable. If people wanna make stupid equations, give people the power to make stupid equations.

**Comment by polytroper** [comment]
Very valid sensible solutions can also be extremely long sometimes. Right now we have a practical cap for daily puzzles because of twitter character limits, but other than that there should never be a hard cap
