### ISSUE TITLE
Last Two Cutscenes Missing from Map

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#439]
### Description

If you click on the white space where they would be you can enter the cutscenes, but they're missing from the map

### Screenshots

<img width="1128" alt="Screenshot 2023-04-24 at 10 13 01 AM" src="https://user-images.githubusercontent.com/122998778/234035518-d2b87abb-82de-4bc8-b3e0-52451ac48cb5.png">

**Comment by polytroper** [comment]
Fixed
