### ISSUE TITLE
Mobile : Edit Function Cutoff

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#443]
### Description

from @Benjamin-Rosenfeld 

### Screenshots

![IMG_3927](https://user-images.githubusercontent.com/122998778/234040952-4adacf4e-0b86-4335-b1cd-ca3b90b227a8.jpg)

**Comment by karamassie** [comment]
is this phone (and which one) or desktop or both?

**Comment by alhardwarehyde** [comment]
Closing because dupe of #427
