### ISSUE TITLE
[FEATURE] SR Performance on Chromebook Reporting

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#451]
### Description

Please comment your Chromebook's specs (eg Lenovo, Dell for example HQ has a Acer Chromebook R11) and the FPS of Levels. the Map, Cutscenes etc 
[www.sinerider.hackclub.dev](https://sinerider.hackclub.dev)

**Comment by Captainexpo-1** [comment]
Dell Chromebook 3100
Specs: [https://www.itechguides.com/product-specs/dell-chromebook-3100-specs/](https://www.itechguides.com/product-specs/dell-chromebook-3100-specs/)

Cutscenes: ~35fps
Levels: ~30fps
Map: ~60fps

**Comment by alhardwarehyde** [comment]
Closing because no action presently
