### ISSUE TITLE
Need design for Puzzle of the Day that accounts for people introduced to SR this way 

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#455]
### Description

Some people are going to be introduced to the game via the puzzle of the day. We need to think thru this:

1. have a "how to play" button. our user testing here showed they didnt know where to type, waht the boxes where for, etc.
2. they won't understand that time as a variable is valid
3. there is NO branding on the page at all. 
4. there is NO HC brand on the page
5. there is no link to about the project
6. there is no link to play the main game

**Comment by polytroper** [comment]
I think the best thing we can do for now is have a different loading page
for puzzle links. This page will simply say “New to sinerider? Learn to
play at sinerider.com” or something like that

**Comment by polytroper** [comment]
Closing, now tracked in

https://github.com/hackclub/sinerider/issues/459
