### ISSUE TITLE
Unexpected results when graphing quadratic functions with fractional coefficients

### ISSUE THREAD

**Issue by astral4** [hackclub/sinerider#46]
In one of the levels, the input $Y = \frac{1}{2} x^2$ shows the graph of $Y = \frac{1}{2x^2}$ instead of $Y = \frac{1}{2} \cdot x^2$. I believe it would be better to display graphs of the latter option by default for these cases.

I took a screenshot of this issue on iOS 15.5 Safari.

![Image of issue](https://user-images.githubusercontent.com/88992929/175700922-b9527e09-03ab-47c3-8d56-e0e6bc2890b4.jpg)

**Comment by profsucrose** [comment]
This has been resolved by the most recent commit where fractional expressions are wrapped with parenthesis during parsing. Thanks for opening the issue!
