### ISSUE TITLE
[FEATURE] Display videos directly in twitter thread

### ISSUE THREAD

**Issue by polytroper** [hackclub/sinerider#460]
### Description

Videos need to be posted directly to twitter through the API, instead of linked. Being able to see the videos in a twitter feed without any interaction required is the core of the whole social media experience and the reason we are doing this on twitter instead of a fully separate leaderboard.

**Comment by grymmy** [comment]
I have collected the following information thus far:

https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update

Documentation leads me to believe that you MUST use the async (chunked) media uploading mechanism.

https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/chunked-media-upload

![Image](https://user-images.githubusercontent.com/43505167/236269156-b6c13a30-c1e7-4e91-b0ea-e0b70bec83aa.png)

webm format is NOT supported, we need to encode using a different format such as mp4 & follow Twitter's suggested bigrates/resolutions/aspect ratio settings, proof:


![Image](https://user-images.githubusercontent.com/43505167/236269452-bd7aa94f-69b8-48c1-be7d-eb7a2e048478.png)

**Comment by grymmy** [comment]
Fixed in https://github.com/developedbytoby/sinerider-twitter-bot/pull/13
