### ISSUE TITLE
[FEATURE] Create final credits scene

### ISSUE THREAD

**Issue by camdan-me** [hackclub/sinerider#462]
### Description

Self-explanatory

**Comment by alhardwarehyde** [comment]
@camdan-me is this a dupe of #233 ?

**Comment by camdan-me** [comment]
No, referring to the actual game credits

**Comment by alhardwarehyde** [comment]
Ah, credits exist in Figma, just need to be added to the game. @ClaireBookworm

**Comment by ClaireBookworm** [comment]
How do I add / should I send it to someone?

**Comment by camdan-me** [comment]
Is the file public? You can link it here and someone can self-assign.

**Comment by karamassie** [comment]
i just played this, and it seems done unless there was an update

**Comment by karamassie** [comment]
@polytroper pls ensure @ClaireBookworm 's latest credit file is swapped in

**Comment by ClaireBookworm** [comment]
Will send the webp in a bit
