### ISSUE TITLE
Fix issue where formulas are too large and display improperly

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#483]
### Description

@ivoinestrachan can you fix this edge case such that we truncate formulas somehow (elipsis or whatever) so that the leaderboard looks clean when formulas are really long?

**Comment by grymmy** [comment]
@ivoinestrachan can you confirm this is fixed and deployed to production and mark it as such if so?

**Comment by ivoinestrachan** [comment]
This is fixed but I want the expression to expand and look nice
