### ISSUE TITLE
Handle case of puzzle submission exceeding time limit

### ISSUE THREAD

**Issue by exu3** [hackclub/sinerider#484]
### Description

When [tweeting](https://twitter.com/eiilla11/status/1654183551607111681?s=20) my puzzle submission, I got a generic error message (the real issue was that my solve exceeded the time limit). The error message should say that there was an error with my submission because it exceeded the time cap of 30 seconds.

This is the url of my submission. https://sinerider.hackclub.dev/?N4IgdghgtgpiBcIAiECWAbAngAgAoFcAvQ9GbAYgEYQAacVAYwGsEQAHIkmAfWroBMAThADuAeUH8YghJQAMCuXQAeCALTy6mBEpBSAZhHzoALgFFlbQTADON1AHswrObRABzBxHQ2EAbVBVeABWLXUANjoTTDY4RH1UZRh+EABfGkCEABYw+A1daNjWBKSUugdJaVYAITSMkCDdbXhKACYomLiQEuS6zLzKHJBmtSHCrp6ykAqpGURa9P6ATly1UJBx4sTe8sq5kABBNIBdOhtSflnfeACG2QBmOgg7GBNWVCgId1sAOgh+CDcc69VKnEAAI0csFY6Ac7lQNhMjCQ+DAtjcCIIxFICBMgnwMDoMEs1jsjjAYgAbtJBKgpKwfpQADpM0j6EwACmUAGosizae4ABYmACUAD1WtyTGpWsE0kA=

### Screenshots

<img width="613" alt="Screenshot 2023-05-04 at 2 37 08 PM" src="https://user-images.githubusercontent.com/72365100/236298249-7dc47ab7-27a0-4271-9e87-eeac3702fcfb.png">

### Additional information

no

**Comment by grymmy** [comment]
@developedbytoby any chance you could look into this?  I looked at the logs and it looked like the scoring service was timing out the solution (>30 sec) but the bot responded with the generic error?

**Comment by grymmy** [comment]
Nevermind @developedbytoby - @JosiasAurel per our conversation, please look into reverting https://github.com/JosiasAurel/sinerider-scoring/commit/35b371e33a6e957a79931b71631090f649eddc1e which caused a regression in scoring solutions that exceed the timeout threshold

**Comment by alhardwarehyde** [comment]
@JosiasAurel does this mean it's good to close?

**Comment by JosiasAurel** [comment]
yes @alhardwarehyde
