### ISSUE TITLE
Clicking the timer no longer stops the game

### ISSUE THREAD

**Issue by camdan-me** [hackclub/sinerider#488]
### Description

When the game is running, the timer turns gray and can only be stopped with enter. It should still be clickable.

**Comment by alhardwarehyde** [comment]
@camdan-me can you give more information? I can't repo on a Mac/Safari

**Comment by alhardwarehyde** [comment]
reopening because other people are having this issue. Don't have specifics yet

**Comment by karamassie** [comment]
other user was using  macbook air and chrome, and saw this randomly. i cant see any specific patterns to when so far

**Comment by Benjamin-Rosenfeld** [comment]
oops I caused this one, Ill commit in a little bit. Solved though

**Comment by karamassie** [comment]
@Benjamin-Rosenfeld pls close this when you submit your PR and TYSM!!!

**Comment by Benjamin-Rosenfeld** [comment]
done

**Comment by polytroper** [comment]
issues close after the PR merges!
