### ISSUE TITLE
Loading Page - HC logo is warped, and needs some small copy edits 

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#489]
### Description

-Hack Club Flag image is Warped, please fix

-Swap out "Version 0.5" with "Public Beta 1.0"

-text change. please change text to: "New daily puzzle published, play now on" [Twitter Logo] [Reddit Logo]

**Comment by Benjamin-Rosenfeld** [comment]
done in pr

**Comment by polytroper** [comment]
@alhardwarehyde The version is correct, 1.0 is for when we leave public beta.

"New daily puzzle published, play now on" doesn't read right to me grammatically 🤔

**Comment by karamassie** [comment]
@bellesea @polytroper we're blocking this task , waiting on final text
