### ISSUE TITLE
Copy edit for Twitter bot tweeting daily puzzle + random selection from 1 of 4 possible tweets

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#494]
### Description

Randomized from one of these four each day. If this is out of scope for launch, please choose “share your best solution "(4th option)

SineRider Daily Puzzle #X: will you be the first to solve it?
SineRider Daily Puzzle #X: where will you place on the leaderboard?
SineRider Daily Puzzle #X: play it now!
SineRider Daily Puzzle #X: share your best solution

**Comment by camdan-me** [comment]
honestly I'd have either just one or way more than 4

**Comment by karamassie** [comment]
hear you @camdan-me -- let's launch with the 4 randomized, and then reassess when we have time

**Comment by polytroper** [comment]
I think we should style the bot after a bumblebee and just have it make random bzzzz noises for all communications

**Comment by polytroper** [comment]
(if it sounds like I am making a joke I am not, I think this would actually be adorable especially if occasionally a single bzzz was all-caps)

**Comment by karamassie** [comment]
i'm onboard... am i being too logical in thinking that makes more sense if we had a character ingame that was a bee? (do we have a random bee somewhere?).

**Comment by grymmy** [comment]
I took a small amount of artistic license here and added the following:

```
    "Will you be the first to solve it?",
    "Where will you place on the leaderboard?",
    "Do you have what it takes?",
    "Are you clever enough to solve this one?",
    "This one might be tricky...",
    "Prepare for your mind to be blown...",
    "Are you in it to win it?",
    "A spectacular puzzle - just for you!",
    "Be careful - this one is tough!",
    "Play it now!",
    "Share your best solution 💖",
    "This one is an absolute monster!",
    "Are you ready for this?  Are you sure?!?!",
    "A puzzle a day keeps the boredom away...",
    "This one is absolutely incredible, just wait, you'll see!",
    "A puzzle like none other!",    
    "A true masterpiece...",
    "A really gnarly one!"

```

**Comment by grymmy** [comment]
For the record, @developedbytoby did a good amount of this work earlier today.
