### ISSUE TITLE
Twitter Bot tweets about daily puzzles need images

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#495]
### Description

currently the bot feed looks like this
<img width="597" alt="Screen Shot 2023-05-05 at 6 10 33 PM" src="https://user-images.githubusercontent.com/99233707/236576974-65b8347c-05bd-45f7-a272-0d0c254bff9f.png">

it needs to look a lot more fun and lively and colorful! (and less bot-like!)
let's add a shot of the puzzle , if possible

<img width="264" alt="Screen Shot 2023-05-05 at 6 13 17 PM" src="https://user-images.githubusercontent.com/99233707/236577295-473acb20-3cd7-48af-8617-bd6507413a5b.png">

If no image allowed or if this is difficult to do by launch, the tweet def needs social card  (image) - very high priority

**Comment by grymmy** [comment]
Fixed in https://github.com/hackclub/sinerider/pull/503

![Image](https://user-images.githubusercontent.com/43505167/236682805-20ac7b2d-b0ed-46f4-8848-de078cb01291.png)
