### ISSUE TITLE
daily puzzle: copy edits needed on 'congrats' message when you solve it . 

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#496]
### Description

Remove giant green 'replay' button, and Change text to this below, please:

Congrats! Your equation solved the puzzle in X seconds and Y characters,
To see how you did on the Leaderboard (hyperlinked & open to new tab), share your solution on Twitter or Reddit (both hyperlinked)

Think you can do better? Try again  (try again hyperlinked. ) **_This replaces that giant green replay button_**

**Comment by JosiasAurel** [comment]
checkout PR #502 
looks like below
![image](https://user-images.githubusercontent.com/47951376/236627222-b1c5194d-0443-4cde-bf31-e40d21c36c2a.png)

**Comment by grymmy** [comment]
@karamassie can you verify that this looks exactly as expected?  @polytroper this PR awaits your feedback/merge

**Comment by karamassie** [comment]
it does if contrats is changed to congrats. @polytroper , do you want to weigh in?

**Comment by JosiasAurel** [comment]
> it does if contrats is changed to congrats. @polytroper , do you want to weigh in?

The typo has already been fixed
