### ISSUE TITLE
Daily puzzle - tweet of player's game solution needs to be more friendly/viral

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#497]
### Description

Currently it feels not-tweetable , so let's make this more human 👍 

"Finally solved sinerider.com daily puzzle 24 "

[[#sinerider puzzle_14 x + 10]]

**Comment by grymmy** [comment]
@karamassie Can you please explain this issue more clearly with exactly the format that is allowed for parsing the puzzle?  i don't think this is sufficient.

**Comment by karamassie** [comment]
@polytroper can you describe the exact text you want here. we've determined that copy is allowable before and after the solution (as long as there is a space)

in the call this was suggested: 
I'm so smart! Here's my solution to the SineRider daily puzzle X

**Comment by karamassie** [comment]
@grymmy fixed with PR #511
