### ISSUE TITLE
Sinerider twitter bot account - get ready for launch

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#498]
### Description

Twtr: change name of account to SineRider (not sineriderbot)

Under “a game about” add , “Play our daily puzzles below”

have it follow hack club, chris walker, and sinerider the game

**Comment by grymmy** [comment]
Note - the account name change to "SineRider" has been performed but there is a review process so it does not take immediate effect.

![Image](https://user-images.githubusercontent.com/43505167/236656795-c2369936-4e01-4cbd-84b2-6f15598c371c.png)

The other changes were made.
