### ISSUE TITLE
daily puzzle video captures of your solution need to be improved pls

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#500]
### Description

they're very abrupt (1second) and low quality.

@polytroper has suggested starting video t=0 plus 5seconds for length.

### Screenshots

<img width="425" alt="Screen Shot 2023-05-05 at 6 59 48 PM" src="https://user-images.githubusercontent.com/99233707/236582261-0b0f699d-14ee-4dfa-aa04-0b0351a37edc.png">

### Additional information

@grymmy assigning to you to determine who this one is good for

**Comment by polytroper** [comment]
I would ideally include a second or two _at_ t=0, basically capturing the moments before you run a solution. I think this moment can be used to showcase the equation, and to help communicate the core mechanic of the game (eventually maybe with a virtual clicking mouse and sound?)

**Comment by karamassie** [comment]
this has been done, though now we're going to slow them down a bit (note from call today)

**Comment by grymmy** [comment]
See https://twitter.com/SineRiderBot/status/1655425537056165892 - video quality is markedly improved compared to reference above.
