### ISSUE TITLE
Daily puzzle on reddit -- reddit link doesnt open to specific puzzle post and there is no way to know which one the player was on

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#523]
### Description

clicking thru the reddit link for the daily puzzle takes me to the subreddit, but not the specific puzzle
because i dont know which puzzle i am on, i'll not know where to post.

**Comment by GalaxyGamingBoy** [comment]
Just started working on this one.
My current plan is to do a redirect endpoint on the sinerider-api to the reddit post.
That endpoint could be accessed like the sinerider.com/puzzle/ URL but it will be sinerider.com/reddit_post/

**Comment by alhardwarehyde** [comment]
closing being resolving PR was pushed
