### ISSUE TITLE
Add Warning if Response is Delayed by < 7mins

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#532]
### Description

Needs Copy.

**Comment by grymmy** [comment]
This would require multiple pieces of work.

1. Add a new sinerider-api method that would expose an estimate of the number of minutes required to process a new work item.  This endpoint could be contextless (assume worst case) or alternatively 
2. Add a new modal dialog in the solution submission flow that would warn the user that bot responses might be slow.

**Comment by grymmy** [comment]
Given that we are solving both the zapier latency issue via direct Twitter integration & the scoring server scaling issues via browserless.io integration, I would argue that the importance of this feature is much less, and probably can be punted on for initial launch.

@alhardwarehyde can you please discuss this with other team members / set expectations surrounding this / remove it from launch requirements?

**Comment by alhardwarehyde** [comment]
Closing this per Conversation with MSW/Graham
