### ISSUE TITLE
Move away from using Zapier for tweet notifications

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#533]
### Description

plz and thank you

**Comment by grymmy** [comment]
This is dependent on a workaround in Zapier that I am not familiar with but apparently @maxwofford @zachlatta are..

**Comment by grymmy** [comment]
Update here - the plan is to move completely away from zapier and implement the integration on our side to (in a practical sense) remove all latency imposed by Zapier.

**Comment by grymmy** [comment]
Fixed in https://github.com/developedbytoby/sinerider-twitter-bot/pull/15
