### ISSUE TITLE
Scoring service sometimes inaccurately marks submissions as timed out

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#534]
There are certain (timing/performance-related) situations where the scoring service will inaccurately mark a submission as invalid due to timeout.  This is not 100% reproducible/deterministic due to it being related to the load on the service and performance of sinerider therein.

**Comment by JosiasAurel** [comment]
I just gave it a try and the game never completes for me.
<img width="242" alt="image" src="https://github.com/hackclub/sinerider/assets/47951376/d0a9f6c2-cadc-4fe8-b877-fec5ab3a8474">
Could someone else try this solution on Puzzle 23?

**Comment by alhardwarehyde** [comment]
@GalaxyGamingBoy can [dupe the issue](https://hackclub.slack.com/archives/C6LHL48G2/p1685635133716879?thread_ts=1685565077.566519&cid=C6LHL48G2)

**Comment by grymmy** [comment]
NOTE - the description of this issue was inaccurate and unhelpful.  I have modified it to detail the actual issue that this issue was originally supposed to encapsulate.
