### ISSUE TITLE
Physics Bug: Formula Made Snowball Clip Through and Fly Away

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#549]
### Description

From HN: I was able to solve the first puzzle by placing a 1/X singularity next to the snowball. It correctly rolled down but the just clipped through and blasted away. It is very hard to cover these sorts of cases with a naive physics model because the numerics get messy very quickly. Very cool project.

### Screenshots

<img width="1038" alt="Screenshot 2023-05-09 at 10 55 33 AM" src="https://github.com/hackclub/sinerider/assets/122998778/66635008-f4fc-4d10-ba4d-a0179e69b562">

**Comment by polytroper** [comment]
In a way this is actually correct behavior, at least in the “point-body” simplified physics model used for the balls. Of course, it should really get stuck wedged in the graph, but there is no way to make that happen without greatly increasing the complexity of our physics engine.
