### ISSUE TITLE
User Feedback: Second Forked Levels Not Working 

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#553]
### Description

Bug from Slack: https://hackclub.slack.com/archives/C6LHL48G2/p1683637550276549

Users can only enter one level when it looks like there should be two unlocked levels

### Screenshots

![IMG_9071](https://github.com/hackclub/sinerider/assets/122998778/48c9e7fc-4f5c-416a-9e7b-c1d3b892cd7a)

**Comment by karamassie** [comment]
needs reproducing. @polytroper , im assuming this is a bug and not by design, tho?

**Comment by polytroper** [comment]
I am pretty sure this is user error but the interface is kind of confusing which I will open a separate issue for
