### ISSUE TITLE
Expressions Not Showing Up Properly in Leaderboard

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#555]
### Description
05/10/23
Expressions should be formatted as they are in game

### Screenshots

<img width="785" alt="Screenshot 2023-05-10 at 10 08 03 AM" src="https://github.com/hackclub/sinerider/assets/122998778/0c9ae0dd-97da-45fd-a51d-1f4dab1d2068">

**Comment by ivoinestrachan** [comment]
@grymmy told me to add a elipsis on it be it extends to long @alhardwarehyde

**Comment by grymmy** [comment]
> @grymmy told me to add a elipsis on it be it extends to long @alhardwarehyde 
> 

To be clear - the goal is for it to "look good" - truncation in extreme cases of lengthy expressions seems reasonable...

**Comment by ivoinestrachan** [comment]
alright thank you for the explanation!

**Comment by alhardwarehyde** [comment]
@JosiasAurel @ivoinestrachan is this issue solved?

**Comment by JosiasAurel** [comment]
I think it is. @ivoinestrachan you can merge my PR if it's okay to you

**Comment by ivoinestrachan** [comment]
oh let me check it out sorry abt that
