### ISSUE TITLE
Leaderboard Should Be Accessed by leaderboard.sinerider.com

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#557]
### Description
05/10/23
What it says above, url is currently https://sinerider-leaderboard.hackclub.dev

**Comment by ivoinestrachan** [comment]
i dont have access to vercel to change DNS settings @grymmy

**Comment by grymmy** [comment]
> i dont have access to vercel to change DNS settings @grymmy 

I believe this is something achievable via PR to hackclub / dns

**Comment by camdan-me** [comment]
you still need to edit the dns config on Vercel, it needs to be updated on both ends

**Comment by grymmy** [comment]
> you still need to edit the dns config on Vercel, it needs to be updated on both ends

Will help ya on this Monday @ivoinestrachan

**Comment by ivoinestrachan** [comment]
Alright thank you!

**Comment by grymmy** [comment]
Did make this modification to the vercel config and confirmed that leaderboard.sinerider.com resolves correctly.  @ivoinestrachan please mark this issue closed at your next convenience if you agree this is fixed.
