### ISSUE TITLE
no option to post my daily puzzle solution to reddit 

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#570]
### Description

When I solve the daily puzzle, it only offers me an option to post on twitter, not reddit. This includes if I start from the reddit link to the daily puzzle itself!

**Comment by GalaxyGamingBoy** [comment]
The link / button to post on reddit was hidden since launch as to not confuse the users.
Uncommenting it now

**Comment by grymmy** [comment]
@GalaxyGamingBoy does that mean this issue can be closed?

**Comment by GalaxyGamingBoy** [comment]
I need to do the pr but otherwise yes

**Comment by grymmy** [comment]
@GalaxyGamingBoy I believe this can be closed with the PR we landed yesterday - can you verify?
