### ISSUE TITLE
Add our Lesson Plan to the READme 

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#613]
### Description

Let's add this to our readme, with a clear and visible callout for teachers
(eg. 

MATH TEACHERS! We have a 60minute lesson plan written by an American High School Math Teacher. Please use it as you like! It explores the process of manipulating graphs by adjusting values within parent functions. The primary focus is on linear, quadratic, and sinusoidal functions.

https://docs.google.com/document/d/1Hwqk98dmBcSFYOcjt27-rLRnKIOCWUOiDHrdgHNT8kA/edit

**Comment by Ehren12** [comment]
I'd like to work on this

**Comment by polytroper** [comment]
Done
