### ISSUE TITLE
Cutscene events replay if you walk backwards

### ISSUE THREAD

**Issue by Omay238** [hackclub/sinerider#616]
### Description

This might be intentional, and most players probably go straight through the cutscene holding right arrow, but it's weird. 

### Screenshots

<img width="1055" alt="Screenshot 2024-01-18 at 11 35 52 AM" src="https://github.com/hackclub/sinerider/assets/70179858/6744819f-d64b-4557-b0bc-637ac1de7870">

### Additional information

It could probably be fixed with extra data, or a progress variable. Once again, I might be able to do this one, I might not.

**Comment by polytroper** [comment]
This is intentional. Moving left/right is supposed to be a sort of “time travel” (notice the time indicator in the bottom/right) allowing users to go back and read earlier dialogue.
