### ISSUE TITLE
Bits of UI stick around in Safari

### ISSUE THREAD

**Issue by aleksrutins** [hackclub/sinerider#620]
### Description

Sometimes, when exiting a level, some of the UI from that level will stay on the screen. This has gotten bad enough before that I’ve had to reload the page in order to use the site.

As far as I know, this only happens on Safari.

### Screenshots

![Screenshot 2024-01-18 at 6 14 26 PM](https://github.com/hackclub/sinerider/assets/24496030/63ea30bd-9f9c-4db9-8745-14afba329bc9)

**Comment by polytroper** [comment]
Does this happen just with the editor UI or also with other elements?

**Comment by aleksrutins** [comment]
I've also had it happen with UI from other levels.

**Comment by polytroper** [comment]
Ok I think I have identified the issue here, working on a fix

**Comment by polytroper** [comment]
Fixed
