### ISSUE TITLE
Click-to-view coordinates don't align with mouse position

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/sinerider#621]
### Description

In any level with not-high res, clicking on the graph and moving the mouse around shows axes and coordinates. However, this doesn't line up with the position of the mouse, which makes it confusing.

### Screenshots

[Screencast from 2024-01-18 18-49-05.webm](https://github.com/hackclub/sinerider/assets/79737178/2bcf90fa-daad-4c94-89d0-81639a75dba4)

### Additional information

On Chromium 120, Fedora Linux 39

**Comment by polytroper** [comment]
Was this with the resolution set to a lower level? I can only seem to replicate this on the lower-res settings.

**Comment by polypixeldev** [comment]
Yes

**Comment by polytroper** [comment]
Fixed
