### ISSUE TITLE
Editor "Copy as Puzzle" links don't work

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/sinerider#624]
### Description

When creating a level in the editor, clicking the share button, copying the link as a puzzle, and then pasting the link into a new window, the puzzle level fails to load. The error thrown in the console is:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'goals')
    at getLevelDatum (World.js:400:40)
    at World (World.js:84:27)
    at main.js:232:15
```
This causes the loading screen to show, but the progress bar stays empty.

**Comment by polytroper** [comment]
Thank you will take a look

**Comment by polytroper** [comment]
Fixed
