### ISSUE TITLE
"Sinerider" title not centered

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#65]
I could live with this except subtitle , "a game about love and..." is, so this looks like an error.

**Comment by polytroper** [comment]
Clarify? There's no screenshot

**Comment by karamassie** [comment]
<img width="810" alt="Screen Shot 2022-07-18 at 10 05 49 PM" src="https://user-images.githubusercontent.com/99233707/179648895-bc7e4081-1e02-4009-b0a8-c84d3df7d373.png">
@polytroper screenie attachede

**Comment by karamassie** [comment]
another screenie. It's just off enough to look not intentional IMO
![Uploading Screen Shot 2022-07-18 at 10.10.28 PM.png…]()

**Comment by karamassie** [comment]
this was my issue, and im happy to close it. reopen if anyone else finds it jarring. low prio for now!
