### ISSUE TITLE
vertical blue line appears in equation box when I click on it

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#67]
... which is different from where the cursor is, making it a wee bit confusing where I'm typing
<img width="132" alt="Screen Shot 2022-07-18 at 8 50 40 AM" src="https://user-images.githubusercontent.com/99233707/179515263-19495682-7f86-406b-8802-931223437dd7.png">

**Comment by karamassie** [comment]
btw, this seems to be because it's an input element which defaults to that light blue (which blends in with background in many of our scenes)

**Comment by polytroper** [comment]
Yeah this isn't great. The Y= should be moved inside the MathQuill node somehow

**Comment by Benjamin-Rosenfeld** [comment]
Fixed issue, ready to close.

**Comment by alhardwarehyde** [comment]
Closing because done
