### ISSUE TITLE
level 6 (below constant lake cutscene): slider starts at -1, but when I go to use it, it switches to positive numbers only

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#71]

**Comment by alhardwarehyde** [comment]
<img width="1302" alt="Screenshot 2023-03-14 at 2 36 33 PM" src="https://user-images.githubusercontent.com/122998778/225104679-95d143e8-ca29-4e7e-8fa1-014f01b3b3cf.png">
Closing this out because this issue appears to be resolved.
