### ISSUE TITLE
Cutscene: Get timing right with equation and sun setting

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/sinerider#72]

**Comment by maxwofford** [comment]
The sun sets really nicely into the vector field– closing for the time being. Please reopen if this wasn't done!

<img width="1250" alt="Screen Shot 2022-08-23 at 11 52 28" src="https://user-images.githubusercontent.com/5891442/186207594-41ebd1a9-7b8a-4611-b884-14bf767e2aa1.png">
