### ISSUE TITLE
Make it clear in Constant Lake that you move by clicking or touching the screen

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/sinerider#74]
Needs to be more clear that you’re not typing formulas to affect ground, you’re dragging ghosts to move story (time) along. Little UI

**Comment by maxwofford** [comment]
Adding the "good first issue" label b/c this can be implemented with adding a quick text line saying "click to move" or something.

**Comment by polytroper** [comment]
@aileencrivera can you please add a text element (like the ones in eden.js) to tell people "Click to move…"

**Comment by alhardwarehyde** [comment]
Closing because this is done

<img width="1341" alt="Screenshot 2023-03-14 at 11 43 01 AM" src="https://user-images.githubusercontent.com/122998778/225056286-8616592a-a0f4-407d-b0d5-371ba1920d31.png">
