### ISSUE TITLE
Axes are being misunderstood as art issues - solution is to add ticks.

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#75]
<img width="447" alt="Screen Shot 2022-07-18 at 9 17 38 AM" src="https://user-images.githubusercontent.com/99233707/179519942-c6de43e3-94bf-492f-a027-4183bf8baaa4.png">

**Comment by karamassie** [comment]
close if as designed

**Comment by alhardwarehyde** [comment]
This also came up in the HQ Play Test. Adding Tick Marks will make it More Clear.

**Comment by Benjamin-Rosenfeld** [comment]
Ill take this one

**Comment by polytroper** [comment]
Awesome thank you so much!

**Comment by Benjamin-Rosenfeld** [comment]
finished
