### ISSUE TITLE
Characters: add animations and expressions

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/sinerider#81]
Make some animated states / sprites. Scarf floats behind when moving, for eg. Make a couple of expressions for story beats.

**Comment by karamassie** [comment]
@ClaireBookworm do we have art assets for this? can you advise where they are, if so

**Comment by ClaireBookworm** [comment]
We don't have art assets for this but I'll work with the sprite artist on this!

**Comment by polytroper** [comment]
This would be awesome but I think it's presently unlikely to happen. Closing
