### ISSUE TITLE
Integrate new ghosts + render

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/sinerider#85]
Integrate the new ghosts (@cadovaaa do we have those all rendered?)

cc: @profsucrose, @neelr

**Comment by maxwofford** [comment]
<img width="775" alt="Screen Shot 2022-08-21 at 11 38 17" src="https://user-images.githubusercontent.com/5891442/185953175-70b29b7a-6a62-4c7e-a213-269a5896f1d4.png">

Can this be closed? Seems like the current build has the latest ghost designs
