### ISSUE TITLE
Level One: replace house sprite with the one attached 

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/sinerider#95]

**Comment by maxwofford** [comment]
Seems like this hasn't been touched for a while, but the house in the trailer seems like it fits in the current design. Can this be closed?
<img width="775" alt="Screen Shot 2022-08-21 at 11 38 17" src="https://user-images.githubusercontent.com/5891442/185798988-51273284-b070-48f0-ae82-160450515fa2.png">
