### ISSUE TITLE
Level One: Add Windmill

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/sinerider#97]
make spinny windmill in back left corner if there’s time (file in folder)

**Comment by karamassie** [comment]
@ClaireBookworm can you link the windmill art asset pls

**Comment by ClaireBookworm** [comment]
Here! https://drive.google.com/drive/u/0/folders/1-57cj8MDsw7A1URPr3ZfArzlyAerLSg3

**Comment by karamassie** [comment]
dupe of #134
